<a href="https://colab.research.google.com/github/vanillaloki9306/Measles-and-Rubella-dataset-project/blob/main/Measles_and_Rubella_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Using Python
# Option 1: pydytuesday python library

import pandas
import pydytuesday

# Download files from the week, which you can then read in locally
pydytuesday.get_date('2025-06-24')

# Option 2: Read directly from GitHub and assign to an object

cases_month = pandas.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_month.csv')
cases_year = pandas.read_csv('https://raw.githubusercontent.com/rfordatascience/tidytuesday/main/data/2025/2025-06-24/cases_year.csv')

Trying to fetch README from: https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2025/2025-06-24/readme.md
Successfully fetched README from: https://raw.githubusercontent.com/rfordatascience/tidytuesday/refs/heads/main/data/2025/2025-06-24/readme.md
Downloading cases_month.csv...
Successfully saved cases_month.csv to /content/cases_month.csv
Downloading cases_year.csv...
Successfully saved cases_year.csv to /content/cases_year.csv
Downloading meta.yaml...
Successfully saved meta.yaml to /content/meta.yaml
Downloading us_measles.png...
Successfully saved us_measles.png to /content/us_measles.png

# Data wrangling

In [ ]:
cases_month

,region,country,iso3,year,month,measles_suspect,measles_clinical,measles_epi_linked,measles_lab_confirmed,measles_total,rubella_clinical,rubella_epi_linked,rubella_lab_confirmed,rubella_total,discarded
0,AFR,Algeria,DZA,2012,1,8.0,6.0,0.0,2.0,8.0,NaN,NaN,NaN,NaN,0.0
1,AFR,Algeria,DZA,2012,2,10.0,10.0,0.0,0.0,10.0,NaN,NaN,NaN,NaN,0.0
2,AFR,Algeria,DZA,2012,3,17.0,17.0,0.0,0.0,17.0,NaN,NaN,NaN,NaN,0.0
3,AFR,Algeria,DZA,2012,4,7.0,5.0,0.0,0.0,5.0,0.0,0.0,1.0,1.0,2.0
4,AFR,Algeria,DZA,2012,5,14.0,11.0,0.0,0.0,11.0,0.0,0.0,3.0,3.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22775,WPR,Viet Nam,VNM,2024,10,379.0,19.0,56.0,256.0,331.0,5.0,0.0,5.0,10.0,48.0
22776,WPR,Viet Nam,VNM,2024,11,584.0,37.0,125.0,347.0,509.0,0.0,0.0,1.0,1.0,75.0
22777,WPR,Viet Nam,VNM,2024,12,588.0,56.0,134.0,338.0,528.0,0.0,0.0,1.0,1.0,60.0
22778,WPR,Viet Nam,VNM,2025,1,156.0,7.0,0.0,124.0,131.0,NaN,NaN,NaN,NaN,25.0
22779,WPR,Viet Nam,VNM,2025,2,22.0,0.0,0.0,20.0,20.0,NaN,NaN,NaN,NaN,2.0

In [ ]:
cases_month.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22780 entries, 0 to 22779
Data columns (total 15 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   region                 22780 non-null  object
 1   country                22780 non-null  object
 2   iso3                   22780 non-null  object
 3   year                   22780 non-null  int64
 4   month                  22780 non-null  int64
 5   measles_suspect        22632 non-null  float64
 6   measles_clinical       22632 non-null  float64
 7   measles_epi_linked     22632 non-null  float64
 8   measles_lab_confirmed  22632 non-null  float64
 9   measles_total          22632 non-null  float64
 10  rubella_clinical       7811 non-null   float64
 11  rubella_epi_linked     7811 non-null   float64
 12  rubella_lab_confirmed  7811 non-null   float64
 13  rubella_total          7811 non-null   float64
 14  discarded              22632 non-null  float64
dtypes: float64(10), int64(2), object(3)
memory usage: 2.6+ MB

In [ ]:
cases_month.describe()

,year,month,measles_suspect,measles_clinical,measles_epi_linked,measles_lab_confirmed,measles_total,rubella_clinical,rubella_epi_linked,rubella_lab_confirmed,rubella_total,discarded
count,22780.000000,22780.000000,22632.000000,22632.000000,22632.000000,22632.000000,22632.000000,7811.000000,7811.000000,7811.000000,7811.000000,22632.000000
mean,2018.253600,6.293547,235.265376,50.708687,38.939069,47.029251,136.677006,19.815901,4.344130,20.066317,44.226347,112.301653
std,3.815709,3.461782,1203.690535,408.194314,748.287331,275.099951,969.226508,283.628969,60.004873,145.382545,335.242009,524.224152
min,2012.000000,1.000000,0.000000,-204.000000,0.000000,0.000000,-195.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2015.000000,3.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000
50%,2018.000000,6.000000,23.000000,0.000000,0.000000,1.000000,2.000000,0.000000,0.000000,3.000000,4.000000,14.000000
75%,2022.000000,9.000000,110.000000,2.000000,0.000000,14.000000,29.000000,0.000000,0.000000,11.000000,15.000000,60.000000
max,2025.000000,12.000000,68051.000000,12730.000000,67728.000000,9936.000000,67929.000000,10856.000000,2476.000000,7039.000000,10856.000000,16443.000000